# MD5: 41e3e83aee30b0cc5a6404e916da0865
set(CFG_PRODUCT_CONTROL_VERSION "141") 

set(CFG_PRODUCT_HISILICON_VERSION hi3660) 

set(CFG_PRODUCT_NV_FILE_MAX_SIZE binfileLimitSize "100") 

set(CFG_PRODUCT_NV_BIN_MODEM_NUNBER bin_modem_number "3") 

set(CFG_PRODUCT_NV_XNV_SUPPORT_PRODUCT_CAT xnv_support_product_cat "1") 

set(CFG_PRODUCT_NV_XNV_PDT_VERSION K3V6_UDP) 

