# MD5: ebc49ef0e1f197bda028723301127e40
set(CFG_FEATURE_BBP_MASTER FEATURE_ON) 

set(CFG_BBP_MASTER_INT_MODE FEATURE_ON) 

set(CFG_FEATURE_BBP_MASTER_CHAN_EXTEND FEATURE_ON) 

set(CFG_FEATURE_BBP_MASTER_CHAN_U2              	 FEATURE_ON) 

set(CFG_FEATURE_POWER_TIMER FEATURE_OFF) 

set(CFG_FEATURE_UE_UICC_MULTI_APP_SUPPORT FEATURE_ON) 

set(CFG_FEATURE_VSIM FEATURE_ON) 

set(CFG_FEATURE_GUC_BBP_TRIG FEATURE_ON) 

set(CFG_FEATURE_GUBBP_HANDSHAKE FEATURE_ON) 

set(CFG_FEATURE_GUDRX_NEWVERSION FEATURE_ON) 

set(CFG_FEATURE_VOS_REDUCE_MEM_CFG FEATURE_OFF) 

set(CFG_FEATURE_OM_BBPLOG FEATURE_OFF) 

set(CFG_FEATURE_RTC_TIMER_DBG FEATURE_OFF) 

set(CFG_FEATURE_MODE_FEM_CHAN_EXT FEATURE_ON) 

set(CFG_FEATURE_PHONE_SC FEATURE_ON) 

set(CFG_FEATURE_SC_SEC_UPDATE FEATURE_ON) 

