# MD5: 26ac23bca51dfbec3c27700e7c28e669
set(CFG_FEATURE_IMS FEATURE_ON) 

set(CFG_FEATURE_LTE_R11 FEATURE_ON) 

set(CFG_FEATURE_LTE_MBMS FEATURE_OFF) 

set(CFG_FEATURE_LTE_NAS_R11 FEATURE_OFF) 

set(CFG_FEATURE_LTE_CDMA_R11 FEATURE_OFF) 

set(CFG_FEATURE_PTM FEATURE_OFF) 

set(CFG_FEATURE_BALONG_CL FEATURE_OFF) 

set(CFG_FEATURE_LTE_CAT_PART_R11 NO) 

set(CFG_TL_PS_MAX_TRCH_NUM_8 YES) 

set(CFG_FEATURE_LPP FEATURE_OFF) 

set(CFG_FEATURE_TDS_WCDMA_DYNAMIC_LOAD FEATURE_OFF) 

set(CFG_FEATURE_CSG FEATURE_ON) 

set(CFG_FEATURE_DFS_SYNC FEATURE_OFF) 

set(CFG_FEATURE_VERSION_V8 FEATURE_OFF) 

set(CFG_FEATURE_DCX0_TLHPA_WRITE_PHY_NV FEATURE_ON) 

set(CFG_FEATURE_CSS_CLOUD_MEMORY_IMPROVE FEATURE_ON) 

