/* MD5: 41e3e83aee30b0cc5a6404e916da0865*/
#if !defined(__PRODUCT_CONFIG_TOOL_H__)
#define __PRODUCT_CONFIG_TOOL_H__

#ifndef PRODUCT_CONTROL_VERSION
#define PRODUCT_CONTROL_VERSION "141" 
#endif 

#ifndef PRODUCT_HISILICON_VERSION
#define PRODUCT_HISILICON_VERSION hi3660 
#endif 

#ifndef PRODUCT_NV_FILE_MAX_SIZE
#define PRODUCT_NV_FILE_MAX_SIZE binfileLimitSize "100" 
#endif 

#ifndef PRODUCT_NV_BIN_MODEM_NUNBER
#define PRODUCT_NV_BIN_MODEM_NUNBER bin_modem_number "3" 
#endif 

#ifndef PRODUCT_NV_XNV_SUPPORT_PRODUCT_CAT
#define PRODUCT_NV_XNV_SUPPORT_PRODUCT_CAT xnv_support_product_cat "1" 
#endif 

#ifndef PRODUCT_NV_XNV_PDT_VERSION
#define PRODUCT_NV_XNV_PDT_VERSION K3V6_UDP 
#endif 

#endif /*__PRODUCT_CONFIG_H__*/ 
