EXTRA_CFLAGS 	+= -Idrivers/hisi/mntn/blackbox/platform_lpm3

obj-$(CONFIG_HISI_LPM3_DEBUG)		+= hisi_lpm3_debug.o
obj-$(CONFIG_HI3XXX_MODEM_ETB)		+= hi3xxx_modem_etb.o
obj-$(CONFIG_HISI_BOOST5V_CONTROL)  += hisi_boost5v_control.o
obj-$(CONFIG_HISI_HISEE)  += hisee.o
subdir-ccflags-$(CONFIG_HISI_BB)		+= -Idrivers/hisi/mntn/blackbox/

