# MD5: d4c04e09911f1c3e2106ceb818b043f7
set(CFG_PRODUCT_CONTROL_VERSION "141") 

set(CFG_PRODUCT_HISILICON_VERSION m533) 

set(CFG_PRODUCT_NV_SPLITFILE binfilesplit "0") 

set(CFG_PRODUCT_NV_FILE_MAX_SIZE binfileLimitSize "10000") 

set(CFG_PRODUCT_NV_BIN_MODEM_NUNBER bin_modem_number "3") 

set(CFG_PRODUCT_NV_XNV_MODEM_NUNBER xnv_modem_number "3") 

set(CFG_PRODUCT_NV_XNV_PDT_VERSION m533) 

