# MD5: db0780ad922d22d9619b581f5c77e3b8
CFG_FEATURE_IMS                                 := FEATURE_ON
CFG_FEATURE_LTE_R11                             := FEATURE_ON
CFG_FEATURE_LTE_MBMS                            := FEATURE_OFF
CFG_FEATURE_LTE_NAS_R11                         := FEATURE_OFF
CFG_FEATURE_LTE_CDMA_R11                        := FEATURE_OFF
CFG_FEATURE_PTM                                 := FEATURE_OFF
CFG_FEATURE_BALONG_CL                           := FEATURE_UE_MODE_CDMA
CFG_FEATURE_LTE_CAT_PART_R11                    := YES
CFG_TL_PS_MAX_TRCH_NUM_8    := YES
CFG_FEATURE_LPP                                 := FEATURE_ON
CFG_FEATURE_TDS_WCDMA_DYNAMIC_LOAD         := FEATURE_ON
CFG_FEATURE_CSG                            := FEATURE_ON
CFG_FEATURE_CSS_CLOUD_MEMORY_IMPROVE           := FEATURE_OFF
