/* MD5: 1ed594c957913d56cb94811aec57858a*/
#if !defined(__PRODUCT_CONFIG_TOOL_H__)
#define __PRODUCT_CONFIG_TOOL_H__

#ifndef PRODUCT_CONTROL_VERSION
#define PRODUCT_CONTROL_VERSION "131" 
#endif 

#ifndef PRODUCT_HISILICON_VERSION
#define PRODUCT_HISILICON_VERSION hi6932 
#endif 

#ifndef PRODUCT_NV_FILE_MAX_SIZE
#define PRODUCT_NV_FILE_MAX_SIZE binfileLimitSize "100" 
#endif 

#ifndef PRODUCT_NV_BIN_MODEM_NUNBER
#define PRODUCT_NV_BIN_MODEM_NUNBER bin_modem_number "1" 
#endif 

#ifndef PRODUCT_NV_XNV_PDT_VERSION
#define PRODUCT_NV_XNV_PDT_VERSION hi6932_udp 
#endif 

#endif /*__PRODUCT_CONFIG_H__*/ 
