# MD5: 72c055f34680847c222415dd53f2a53e
set(CFG_TENSILICA_BUILDS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RE-2014.5-linux) 

set(CFG_TENSILICA_TOOLS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RE-2014.5-linux) 

set(CFG_FEATURE_HIFI FEATURE_ON) 

set(CFG_FEATURE_HIFI_USE_ICC FEATURE_ON) 

set(CFG_FEATURE_MBB_MODULE_AUDIO FEATURE_ON) 

set(CFG_FEATURE_VOICE_UP FEATURE_OFF) 

set(CFG_FEATURE_DTMF FEATURE_ON) 

set(CFG_FEATURE_VOICE_INBAND_DTMF_ELIMINATE FEATURE_ON) 

