# maxim smartPA driver

obj-$(CONFIG_ANC_HS_MODULE) += anc_hs_module/
obj-$(CONFIG_EARPA) += earpiece_pa/
obj-$(CONFIG_INVERT_HS) += invert_hs/
obj-$(CONFIG_TFA9895) += tfa9895/
obj-$(CONFIG_TPS65133) += tps65133/
obj-$(CONFIG_MAXIM)	+= maxim/
obj-$(CONFIG_DEVICEBOXID)	+= deviceboxID/
obj-$(CONFIG_AK4376)	+= ak4376/
obj-$(CONFIG_HIFI_VIR_DAI)	+= hifi_vir_dai/
obj-$(CONFIG_AUDIO_DMD)	+= audio_dmd/

