
/*****************************************************************************
  1 头文件包含
*****************************************************************************/
#include "errlog_cfg.h"

#ifdef __cplusplus
  #if __cplusplus
  extern "C"{
  #endif
#endif

//#define    THIS_FILE_ID        PS_FILE_ID_ERRLOG_CFG_C

/*****************************************************************************
  2 全局变量声明
*****************************************************************************/

#if (FEATURE_ON == FEATURE_PTM)
/* Warning：代码自动生成区域，不能手工改动 begin */
/* TODO: g_aulModemErrRept hash_value:001e13bf53cc4cff835a0c12e5a166fc */
/* TODO: python search flag satrt */
int g_aulModem0ErrRept[][3]=
{
    /* GU ErrLog 上报相关 Item:13 */
    {FAULT_ID_GU_ERR_LOG_REPT, I0_WUEPS_PID_MMC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_UEPS_PID_MTA, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_WUEPS_PID_USIM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_UEPS_PID_GAS, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_UEPS_PID_SN, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, WUEPS_PID_WRR, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_DSP_PID_APM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, PS_PID_ERRC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, TPS_PID_RRC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, PS_PID_MM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, TPS_PID_MAC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, PS_PID_MAC_UL, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, TLPHY_PID_RTTAGENT, 0},


#if (FEATURE_ON == FEATURE_UE_MODE_CDMA)
    /* 注册失败 Item:15 */
    {FAULT_ID_1X_REG_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_REG_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_REG_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_MEASURE_INFO},

    /* 语音质量差 Item:2 */
    {FAULT_ID_1X_VOICE_QUALITY_BAD, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_VOICE_QUALITY_BAD, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},

    /* 通用异常收集 Item:4 */
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_TCA_RCV_FAIL},

    /* 短息接收失败 Item:18 */
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 短息发送失败 Item:19 */
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I0_UEPS_PID_XSMS, NAS_ERR_LOG_ALM_XSMS_SND_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* PS会话异常 Item:13 */
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* PS呼叫失败 Item:16 */
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I0_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_CDMA_PS_CALL_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, MSPS_PID_PPPC, PPP_ERR_LOG_ALM_ID_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* PS断链 Item:15 */
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I0_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_CDMA_PS_DISC_EXCEPTION},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, MSPS_PID_PPPC, PPP_ERR_LOG_ALM_ID_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* CL模式下HRPD或LTE丢网Item:15 */
    {FAULT_ID_HRPD_OR_LTE_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_SEARCH_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_RESEL_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_REDIRECT_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PILOT_SEARCH_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_SLAVE_MEAS_INFO},

    /* CL模式下HRPD或LTE掉网恢复 Item:5 */
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, UEPS_PID_HSD, NAS_ERR_LOG_ALM_HRPD_OOS_SEARCH},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I0_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_CL_OOS_SEARCH},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},

    /* CL多模搜网过程 Item:6 */
    {FAULT_ID_CL_OOS_SEARCH, I0_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_CL_OOS_SEARCH},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_RESEL_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_REDIRECT_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_CL_OOS_SEARCH, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},

    /* 1x主叫失败 Item:19 */
    {FAULT_ID_1X_MO_CALL_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, I0_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_1X_CS_MO_CALL_EXCEPTION},
    {FAULT_ID_1X_MO_CALL_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x掉网恢复 Item:2 */
    {FAULT_ID_1X_OOS_RECOVERY, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_OOS_RECOVERY, UEPS_PID_XSD, NAS_ERR_LOG_ALM_1X_OOS_SEARCH},

    /* 1x掉网 Item:11 */
    {FAULT_ID_1X_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_SYNC_FAIL},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_OOS, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PILOT_SEARCH_FAIL},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x掉话 Item:14 */
    {FAULT_ID_1X_CALL_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_CALL_EXCEPTION, I0_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_1X_CS_CONVERSATION_EXCEPTION},
    {FAULT_ID_1X_CALL_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_FAIL_REVERT},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_TCH_HANDOFF_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_CALL_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x被叫失败 Item:18 */
    {FAULT_ID_1X_MT_CALL_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

#endif

};

#if (FEATURE_ON == FEATURE_MULTI_MODEM)
int g_aulModem1ErrRept[][3]=
{
    /* GU ErrLog 上报相关 Item:6 */
    {FAULT_ID_GU_ERR_LOG_REPT, I1_WUEPS_PID_MMC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_UEPS_PID_MTA, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_WUEPS_PID_USIM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_UEPS_PID_GAS, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_UEPS_PID_SN, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_DSP_PID_APM, 0},


#if (FEATURE_ON == FEATURE_UE_MODE_CDMA)
    /* 注册失败 Item:15 */
    {FAULT_ID_1X_REG_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_REG_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_REG_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_MEASURE_INFO},

    /* 语音质量差 Item:2 */
    {FAULT_ID_1X_VOICE_QUALITY_BAD, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_VOICE_QUALITY_BAD, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},

    /* 通用异常收集 Item:4 */
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_TCA_RCV_FAIL},

    /* 短息接收失败 Item:18 */
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 短息发送失败 Item:19 */
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I1_UEPS_PID_XSMS, NAS_ERR_LOG_ALM_XSMS_SND_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* PS会话异常 Item:13 */
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* PS呼叫失败 Item:16 */
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I1_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_CDMA_PS_CALL_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, MSPS_PID_PPPC, PPP_ERR_LOG_ALM_ID_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* PS断链 Item:15 */
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I1_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_CDMA_PS_DISC_EXCEPTION},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, MSPS_PID_PPPC, PPP_ERR_LOG_ALM_ID_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* CL模式下HRPD或LTE丢网Item:15 */
    {FAULT_ID_HRPD_OR_LTE_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_SEARCH_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_RESEL_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_REDIRECT_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PILOT_SEARCH_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_SLAVE_MEAS_INFO},

    /* CL模式下HRPD或LTE掉网恢复 Item:5 */
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, UEPS_PID_HSD, NAS_ERR_LOG_ALM_HRPD_OOS_SEARCH},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I1_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_CL_OOS_SEARCH},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},

    /* CL多模搜网过程 Item:6 */
    {FAULT_ID_CL_OOS_SEARCH, I1_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_CL_OOS_SEARCH},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_RESEL_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_REDIRECT_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_CL_OOS_SEARCH, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},

    /* 1x主叫失败 Item:19 */
    {FAULT_ID_1X_MO_CALL_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, I1_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_1X_CS_MO_CALL_EXCEPTION},
    {FAULT_ID_1X_MO_CALL_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x掉网恢复 Item:2 */
    {FAULT_ID_1X_OOS_RECOVERY, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_OOS_RECOVERY, UEPS_PID_XSD, NAS_ERR_LOG_ALM_1X_OOS_SEARCH},

    /* 1x掉网 Item:11 */
    {FAULT_ID_1X_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_SYNC_FAIL},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_OOS, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PILOT_SEARCH_FAIL},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x掉话 Item:14 */
    {FAULT_ID_1X_CALL_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_CALL_EXCEPTION, I1_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_1X_CS_CONVERSATION_EXCEPTION},
    {FAULT_ID_1X_CALL_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_FAIL_REVERT},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_TCH_HANDOFF_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_CALL_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x被叫失败 Item:18 */
    {FAULT_ID_1X_MT_CALL_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

#endif

};

#if(3 == MULTI_MODEM_NUMBER)
int g_aulModem2ErrRept[][3]=
{
    /* GU ErrLog 上报相关 Item:6 */
    {FAULT_ID_GU_ERR_LOG_REPT, I2_WUEPS_PID_MMC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I2_UEPS_PID_MTA, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I2_WUEPS_PID_USIM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I2_UEPS_PID_GAS, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I2_UEPS_PID_SN, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I2_DSP_PID_APM, 0},


#if (FEATURE_ON == FEATURE_UE_MODE_CDMA)
    /* 注册失败 Item:15 */
    {FAULT_ID_1X_REG_FAIL, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_REG_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_REG_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_MEASURE_INFO},

    /* 语音质量差 Item:2 */
    {FAULT_ID_1X_VOICE_QUALITY_BAD, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_VOICE_QUALITY_BAD, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},

    /* 通用异常收集 Item:4 */
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_TCA_RCV_FAIL},

    /* 短息接收失败 Item:18 */
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 短息发送失败 Item:19 */
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I2_UEPS_PID_XSMS, NAS_ERR_LOG_ALM_XSMS_SND_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* PS会话异常 Item:13 */
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* PS呼叫失败 Item:16 */
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I2_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_CDMA_PS_CALL_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, MSPS_PID_PPPC, PPP_ERR_LOG_ALM_ID_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* PS断链 Item:15 */
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I2_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_CDMA_PS_DISC_EXCEPTION},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, MSPS_PID_PPPC, PPP_ERR_LOG_ALM_ID_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* CL模式下HRPD或LTE丢网Item:15 */
    {FAULT_ID_HRPD_OR_LTE_OOS, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_SEARCH_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_RESEL_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_REDIRECT_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PILOT_SEARCH_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_SLAVE_MEAS_INFO},

    /* CL模式下HRPD或LTE掉网恢复 Item:5 */
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, UEPS_PID_HSD, NAS_ERR_LOG_ALM_HRPD_OOS_SEARCH},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I2_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_CL_OOS_SEARCH},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},

    /* CL多模搜网过程 Item:6 */
    {FAULT_ID_CL_OOS_SEARCH, I2_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_CL_OOS_SEARCH},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_RESEL_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_REDIRECT_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_CL_OOS_SEARCH, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},

    /* 1x主叫失败 Item:19 */
    {FAULT_ID_1X_MO_CALL_FAIL, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, I2_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_1X_CS_MO_CALL_EXCEPTION},
    {FAULT_ID_1X_MO_CALL_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x掉网恢复 Item:2 */
    {FAULT_ID_1X_OOS_RECOVERY, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_OOS_RECOVERY, UEPS_PID_XSD, NAS_ERR_LOG_ALM_1X_OOS_SEARCH},

    /* 1x掉网 Item:11 */
    {FAULT_ID_1X_OOS, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_SYNC_FAIL},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_OOS, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PILOT_SEARCH_FAIL},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x掉话 Item:14 */
    {FAULT_ID_1X_CALL_EXCEPTION, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_CALL_EXCEPTION, I2_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_1X_CS_CONVERSATION_EXCEPTION},
    {FAULT_ID_1X_CALL_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_FAIL_REVERT},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_TCH_HANDOFF_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_CALL_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x被叫失败 Item:18 */
    {FAULT_ID_1X_MT_CALL_FAIL, I2_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

#endif

};
#endif
#endif
/* TODO: python search flag end */
/* Warning：代码自动生成区域，不能手工改动 end */
#endif

/*****************************************************************************
  3 函数申明
*****************************************************************************/


VOS_INT32 ErrLog_GetErrReptAddrAndSize(
    VOS_UINT32                           ulModemId,
    VOS_UINT_PTR                        *pulErrLogAddr,
    VOS_UINT32                          *pulsize
)
{
#if (FEATURE_ON == FEATURE_PTM)
    if (MODEM_ID_0 == ulModemId)
    {
        *pulErrLogAddr = (VOS_UINT_PTR)g_aulModem0ErrRept;
        *pulsize = sizeof(g_aulModem0ErrRept);
    }
#if ( FEATURE_ON == FEATURE_MULTI_MODEM )
    else if (MODEM_ID_1 == ulModemId)
    {
        *pulErrLogAddr = (VOS_UINT_PTR)g_aulModem1ErrRept;
        *pulsize = sizeof(g_aulModem1ErrRept);

    }
#if (3 == MULTI_MODEM_NUMBER)
    else if (MODEM_ID_2 == ulModemId)
    {
        *pulErrLogAddr = (VOS_UINT_PTR)g_aulModem2ErrRept;
        *pulsize = sizeof(g_aulModem2ErrRept);
    }
#endif
#endif
    else
    {
        return VOS_ERR;
    }

    return VOS_OK;

#else
    return VOS_ERR;

#endif

}


VOS_INT32 ErrLog_GetPidAndAlarmId(
    VOS_UINT32                          ulModemId,
    VOS_UINT32                          ulFaultId,
    ERR_LOG_ALARM_STRU                 *paustAlarmArray,
    VOS_UINT32                         *pulAlarmNum
)
{
    VOS_UINT_PTR                        ulErrLogAddr = VOS_NULL;
    VOS_UINT32                          ulsize;
    VOS_UINT32                          ulCount = 0;
    VOS_UINT32                          i;
    VOS_UINT32                          (*pulErrLogArry)[3];

    if (VOS_NULL_PTR == paustAlarmArray)
    {
        return VOS_ERR;
    }

    if (VOS_OK != ErrLog_GetErrReptAddrAndSize(ulModemId, &ulErrLogAddr, &ulsize))
    {
        return VOS_ERR;
    }

    pulErrLogArry = (VOS_UINT32(*)[])ulErrLogAddr;

    for (i=0; i < (ulsize / (3 * sizeof(VOS_UINT32))); i++)
    {
        if (ulFaultId == pulErrLogArry[i][0])
        {
            if (FAULT_ID_CONTAIN_ALARM_ID_MAX_NUM <= ulCount)
            {
                return VOS_ERR;
            }

            paustAlarmArray[ulCount].ulPid      = pulErrLogArry[i][1];
            paustAlarmArray[ulCount].ulAlarmID  = pulErrLogArry[i][2];
            ulCount++;
        }
    }

    *pulAlarmNum = ulCount;

    return VOS_OK;
}


VOS_BOOL ErrLog_IsContainPID(
    VOS_UINT32                         *PaulPidArray,
    VOS_UINT32                          ulPidArrayLen,
    VOS_UINT32                          ulDstPid
)
{
    VOS_UINT32                          i;

    for (i=0; i < ulPidArrayLen; i++)
    {
        if (ulDstPid == PaulPidArray[i])
        {
            return VOS_TRUE;
        }
    }

    return VOS_FALSE;
}


VOS_INT32 ErrLog_GetErrlogPid(
    VOS_UINT32                          ulModemId,
    VOS_UINT32                         *PaulPidArray,
    VOS_UINT32                         *pulPidNum
)
{
    VOS_UINT_PTR                        ulErrLogAddr = VOS_NULL;
    VOS_UINT32                          ulsize;
    VOS_UINT32                          ulCount = 0;
    VOS_UINT32                          i;
    VOS_UINT32                          (*pulErrLogArry)[3];

    if (VOS_NULL_PTR == PaulPidArray)
    {
        return VOS_ERR;
    }

    if (VOS_OK != ErrLog_GetErrReptAddrAndSize(ulModemId, &ulErrLogAddr, &ulsize))
    {
        return VOS_ERR;
    }

    pulErrLogArry = (VOS_UINT32(*)[])ulErrLogAddr;

    for (i=0; i < (ulsize / (3 * sizeof(VOS_UINT32))); i++)
    {
        if (0 == i)
        {
            PaulPidArray[0] = pulErrLogArry[i][1];
            ulCount++;
            continue;
        }

        if (VOS_TRUE != ErrLog_IsContainPID(PaulPidArray, ulCount, pulErrLogArry[i][1]))
        {
            if (ERR_LOG_PID_MAX_NUM <= ulCount)
            {
                return VOS_ERR;
            }

            PaulPidArray[ulCount] = pulErrLogArry[i][1];
            ulCount++;
        }
    }

    *pulPidNum = ulCount;

    return VOS_OK;
}


#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif

