ccflags-y += -Idrivers/media/huawei/camera/sensor
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/csi
ccflags-y += -Idrivers/media/huawei/camera/platform

obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX298) += imx298.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX230) += imx230.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX179) += imx179.o
